spring.application.name=backend
server.port=8080

# H2 Database Configurations
spring.datasource.url=postgresql://my_spring_db_cv9j_user:3A7oO05vAYqEjGNpfRfkhoNWQjL6MiCF@dpg-d975oqojs32c73bq8b90-a.singapore-postgres.render.com/my_spring_db_cv9j
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=my_spring_db_cv9j_user
spring.datasource.password=3A7oO05vAYqEjGNpfRfkhoNWQjL6MiCF
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

# Disable security frame options to allow H2 console in iframe
spring.headers.frame-options=sameorigin

# Fixed Admin Account details
admin.email=admin@kabadbecho.com
admin.password=admin123

# Mail Configurations (Mock SMTP for Dev - e.g. Mailtrap or standard Gmail relay config placeholders)
spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=no-reply@kabadbecho.com
spring.mail.password=mockpassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
